import type { Metadata } from "next";
import { fonts } from "./theme/fonts";
import ChakraProvider from "./components/providers/chakra";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fonts.ppNeuman.className}>
        <ChakraProvider>{children}</ChakraProvider>
      </body>
    </html>
  );
}
